export interface TSiteVisit {
    unique_visit_id: string,
    minara_site_id: string,
    site_visit_ref: string,
    site_visitor_name: string,
    access_creation_datetime: Date,
    site_coordinates: string,
    site_login_datetime: Date,
    site_logout_datetime: Date,
    activity_category: string,
    activity_type: string,
    access_status: string,
    remarks: string,
    dg1_fuel_level: string,
    dg2_fuel_level: string,
    dg1_engine_run_hours: string,
    dg2_engine_run_hours: string,
    luku_meter_reading: string,
    dg1_galooli_fuel_app_amount: string,
    dg2_galooli_fuel_app_amount: string,
    tenants_clamp_meter_reading: string,
    dg_service_check: string,
}